# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ppAWIr5cypR-d4bgb5WUyUqAMM1m-CLp

# Pattern 1
"""

# 1. Install specific, stable versions to prevent environment conflicts
!pip install gensim==4.3.2 scikit-learn==1.3.2 matplotlib==3.8.2 numpy==1.26.4 scipy==1.11.4 --quiet

import gensim.downloader as api
import numpy as np
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

print("Loading GloVe model (100D). This may take a minute...")
model = api.load("glove-wiki-gigaword-100")

print("\n=== Word Relationships ===")
print("Similarity (king, queen):", round(model.similarity("king", "queen"), 4))

# Vector arithmetic: king - man + woman = queen
analogy = model.most_similar(positive=["king", "woman"], negative=["man"], topn=1)
print(f"Analogy (king - man + woman) = {analogy[0][0]} (Score: {analogy[0][1]:.4f})")

print("\n=== PCA Visualization ===")
words = ["king", "queen", "man", "woman", "prince", "princess", "france", "paris", "italy", "rome"]
vectors = np.array([model[w] for w in words])

# Reduce dimensions from 100D to 2D
reduced = PCA(n_components=2).fit_transform(vectors)

plt.figure(figsize=(8, 6))
plt.scatter(reduced[:, 0], reduced[:, 1], color='crimson')

for i, word in enumerate(words):
    plt.annotate(word, (reduced[i, 0] + 0.05, reduced[i, 1] + 0.05))

plt.title("Semantic Relationships in 2D Space")
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

# 1. Install locked dependencies
!pip uninstall numpy scipy -y --quiet
!pip install numpy==1.26.4 scipy==1.11.4 --upgrade --force-reinstall --quiet
!pip install gensim==4.3.2 scikit-learn==1.3.2 matplotlib==3.8.2 --no-deps --quiet --force-reinstall

import gensim.downloader as api
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

print("Loading GloVe model...")
model = api.load("glove-wiki-gigaword-100")

tech_words = [
    "computer", "software", "hardware", "internet", "network",
    "database", "algorithm", "python", "cloud", "security"
]

# Ensure words exist in vocabulary
valid_words = [w for w in tech_words if w in model]
vectors = np.array([model[w] for w in valid_words])

# Dimensionality reduction
reduced = PCA(n_components=2).fit_transform(vectors)

# Visualization
plt.figure(figsize=(8, 6))
plt.scatter(reduced[:, 0], reduced[:, 1], color='dodgerblue')

for i, word in enumerate(valid_words):
    plt.annotate(word, (reduced[i, 0] + 0.03, reduced[i, 1] + 0.03))

plt.title("Technology Word Embeddings (PCA Projection)")
plt.grid(True, linestyle='--', alpha=0.5)
plt.show()

print("\n=== Semantic Analysis ===")
print("Similarity (internet, network):", round(model.similarity("internet", "network"), 4))

print("\nTop 3 words similar to 'cloud':")
for w, score in model.most_similar("cloud", topn=3):
    print(f" - {w} ({score:.4f})")

"""# Pattern 2

"""

# 1. Install locked dependencies
!pip install gensim==4.3.2 --quiet

from gensim.models import Word2Vec
from gensim.utils import simple_preprocess

# Domain-specific corpus
corpus = [
    "The doctor prescribed antibiotics for the infection",
    "The patient was diagnosed with diabetes and hypertension",
    "Surgery was performed to remove the tumor",
    "The nurse monitored the patient's vital signs",
    "Cancer treatment includes chemotherapy and radiation therapy"
]

# Tokenize sentences
processed_corpus = [simple_preprocess(sentence) for sentence in corpus]

# Train the model
print("Training custom Word2Vec model on Medical Corpus...")
model = Word2Vec(
    sentences=processed_corpus,
    vector_size=100,
    window=5,
    min_count=1,
    workers=4
)

print("\n=== Similarity Results ===")
print("Words associated with 'doctor':")
for w, score in model.wv.most_similar("doctor", topn=3):
    print(f" - {w} ({score:.4f})")

print("\nSimilarity score (cancer, tumor):", round(model.wv.similarity("cancer", "tumor"), 4))

# 1. Install locked dependencies
!pip install gensim==4.3.2 transformers==4.35.2 torch==2.1.2 --quiet

from gensim.models import Word2Vec
from gensim.utils import simple_preprocess
from transformers import pipeline

# Train AI-domain Word2Vec
corpus = [
    "Artificial intelligence improves automation",
    "Machine learning learns from data",
    "Deep learning uses neural networks",
    "AI helps in robotics and automation"
]
model = Word2Vec([simple_preprocess(s) for s in corpus], vector_size=100, window=5, min_count=1)

# Retrieve contextually similar words to enrich the prompt
similar_words = [w for w, _ in model.wv.most_similar("ai", topn=2)]

base_prompt = "Explain the benefits of AI in healthcare."
enriched_prompt = f"Explain the benefits of AI, {similar_words[0]}, and {similar_words[1]} in healthcare."

print("Base Prompt     :", base_prompt)
print("Enriched Prompt :", enriched_prompt)

# Initialize Generative AI
print("\nLoading GPT-2 Generator...")
generator = pipeline("text-generation", model="gpt2")

# Generate and compare texts
print("\n=== Generative Outputs ===")
out_base = generator(base_prompt, max_length=40, pad_token_id=50256, truncation=True)
out_enriched = generator(enriched_prompt, max_length=40, pad_token_id=50256, truncation=True)

print("\n[From Base Prompt]:\n", out_base[0]['generated_text'])
print("\n[From Enriched Prompt]:\n", out_enriched[0]['generated_text'])

# 1. Install locked dependencies
!pip install gensim==4.3.2 nltk==3.8.1 --quiet

import nltk
from gensim.models import Word2Vec
from nltk.corpus import brown

# Download dataset and preprocess
nltk.download('brown', quiet=True)
processed = [[w.lower() for w in sent] for sent in brown.sents()]

print("Training Word2Vec on the Brown Corpus...")
model = Word2Vec(processed, vector_size=100, window=5, min_count=2)

print("\n=== Interactive Story Generator ===")
seed_word = input("Enter a seed word (e.g., king, ocean, mountain): ").lower()

try:
    # Fetch similar words to weave into the narrative
    words = [w for w, _ in model.wv.most_similar(seed_word, topn=5)]

    story = (
        f"\nOnce upon a time, a {seed_word} met a {words[0]} and a {words[1]}. "
        f"Together, they explored {words[2]} places, remained {words[3]} during hardships, "
        f"and eventually realized that finding {words[4]} is the true joy of life."
    )
    print("\n[Generated Tale]:", story)

except KeyError:
    print("\n❌ Error: Word not found in vocabulary. Try a more common English word.")

"""# Pattern 3

"""

# 1. Install locked dependencies
!pip install transformers==4.35.2 torch==2.1.2 --quiet

from transformers import pipeline

class SentimentAnalyzer:
    """A highly encapsulated class for sentiment analysis."""

    def __init__(self):
        print("Initializing Sentiment Pipeline...")
        self.analyzer = pipeline("sentiment-analysis")

    def analyze(self, texts):
        print("\n=== Sentiment Analysis Results ===")
        results = self.analyzer(texts)
        for idx, (text, res) in enumerate(zip(texts, results), 1):
            label = res['label']
            conf = res['score']
            print(f"{idx}. [{label}] (Conf: {conf:.2f}) | \"{text}\"")

if __name__ == "__main__":
    sample_data = [
        "I absolutely love this product! It exceeded expectations.",
        "This is the worst customer service experience I have ever had.",
        "The food was okay, but nothing particularly special."
    ]

    app = SentimentAnalyzer()
    app.analyze(sample_data)

# 1. Install locked dependencies
!pip install transformers==4.41.0 torch==2.2.0 accelerate --quiet

from transformers import pipeline
import textwrap

print("Loading DistilBART Summarization Model...")
summarizer = pipeline("summarization", model="sshleifer/distilbart-cnn-12-6")

input_text = """
Artificial Intelligence (AI) is a rapidly evolving field of computer science that aims
to create systems capable of performing tasks that typically require human intelligence.
These tasks include problem-solving, learning, reasoning, perception, and language
understanding. AI technologies have seen significant growth due to advances in machine
learning, deep learning, and the availability of large datasets. In recent years, AI
has been applied across various domains such as healthcare, finance, transportation,
and education, fundamentally altering how industries operate.
"""

print("\n=== ORIGINAL TEXT ===")
print(textwrap.fill(input_text.strip(), width=80))

# Generate constraints-based summary
summary_result = summarizer(input_text, max_length=50, min_length=20, do_sample=False)

print("\n=== GENERATED SUMMARY ===")
print(textwrap.fill(summary_result[0]['summary_text'], width=80))

# 1. Install locked dependencies
!pip install cohere==4.57 --quiet

import cohere

# NOTE: Insert your actual key below before the exam
API_KEY = "YOUR_API_KEY_HERE"

try:
    # Initialize client
    co = cohere.Client(API_KEY)

    text = "AI is transforming industries globally but is raising widespread ethical concerns regarding bias and job displacement."
    prompt = f"Analyze the following text and provide:\n1. A Title\n2. Key Points\n\nText: {text}"

    print("Sending Request to Cohere API...")
    response = co.chat(
        message=prompt,
        model="command-r-08-2024",
        temperature=0.3
    )

    print("\n=== Cohere Response ===")
    print(response.text)

except Exception as e:
    print("\n❌ Execution Error. Did you replace 'YOUR_API_KEY_HERE' with a valid key?")
    print(f"System Detail: {e}")

"""# Pattern 4

"""

# 1. Install locked dependencies
!pip install wikipedia-api==0.6.0 pydantic==2.5.3 --quiet

from pydantic import BaseModel, Field
import wikipediaapi
import re

# Structured Data Model
class InstitutionDetails(BaseModel):
    founder: str = Field(default="N/A", description="Founder of the institution")
    founded: str = Field(default="N/A", description="Founding year")
    summary: str = Field(..., description="Brief summary of the page")

def fetch_institution(name: str) -> InstitutionDetails:
    wiki = wikipediaapi.Wikipedia("AcademicExtractor/1.0", "en")
    page = wiki.page(name)

    if not page.exists():
        raise ValueError(f"Institution '{name}' not found on Wikipedia.")

    text = page.text
    year_match = re.search(r"\b(18|19|20)\d{2}\b", text)
    founder_match = re.search(r"founded by ([A-Z][a-zA-Z\s]+)", text, re.IGNORECASE)

    return InstitutionDetails(
        founder=founder_match.group(1).strip() if founder_match else "N/A",
        founded=year_match.group() if year_match else "N/A",
        summary=page.summary[:200] + "..."
    )

# Execution block
print("=== Wikipedia Institution Scraper ===")
inst_name = input("Enter Institution Name (e.g., Stanford University): ")

try:
    details = fetch_institution(inst_name)
    print("\n[Extracted Data]")
    print(f"Founder : {details.founder}")
    print(f"Founded : {details.founded}")
    print(f"Summary : {details.summary}")
except Exception as e:
    print(f"\n❌ Error: {e}")